name: Stash-Buttplug
description: Connects StashApp to Buttplug.io (Intiface) and syncs Funscripts.
version: 1.0
url: https://github.com/generic/stash-buttplug
ui:
  javascript:
    - main.js
tasks:
  - name: Start Buttplug Bridge
    description: Starts the local server to allow accessing funscript files. Run this once per session.
    exec: [python, bridge.py]
